version: '3.8'

services:
  e2e-tests:
    build: .
    container_name: open-supply-hub-e2e-tests
    environment:
      BASE_URL: https://test.os-hub.net
      USER_EMAIL: {email}
      USER_PASSWORD: {password}
      AUTH_TOKEN: {token}
      USER_ADMIN_EMAIL: {admin_email}
      USER_ADMIN_PASSWORD: {admin_password}
      USER_API_EMAIL: {api_email}
      USER_API_PASSWORD: {api_password}
      ENVIRONMENT: {environment}
      VERSION_TAG: {version_tag}
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
  
  report-server:
    image: nginx:alpine
    container_name: playwright-report-server
    ports:
      - "9323:80"
    volumes:
      - ./playwright-report:/usr/share/nginx/html:ro
    depends_on:
      - e2e-tests
