name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'test'
        type: choice
        options: [test, staging, production]
permissions:
  contents: write
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      USER_EMAIL: ${{ vars.USER_EMAIL }}
      USER_PASSWORD: ${{ vars.USER_PASSWORD}}
      USER_ADMIN_EMAIL: ${{ vars.USER_ADMIN_EMAIL }}
      USER_ADMIN_PASSWORD: ${{ vars.USER_ADMIN_PASSWORD }}
      USER_API_EMAIL: ${{ vars.USER_API_EMAIL }}
      USER_API_PASSWORD: ${{ vars.USER_API_PASSWORD }}
    steps:
      - name: Display environment
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Push to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          git --work-tree playwright-report add --all
          git --work-tree playwright-report commit -m 'Deploy'
          git push origin HEAD:gh-pages --force
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
